### ISSUE TITLE
TimeoutError: ResourceRequest timed out

### ISSUE THREAD

**Issue by EtcFly** [loclink/waline-service#1]
使用这个一键部署的时候, 可以正常运行起来`npm run dev`, 但是此时通过http:[ip]:[port]的方式去新增评论, 会报如下的错误
```js
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/opt/waline-service/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/opt/waline-service/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```
请问是什么原因造成的, `MongoDB`数据库安装都是好的, 单独测试是正常的

**Comment by loclink** [comment]
这个报错是请求超时了，关于如何发送请求以及请求方式请前往：[waline](https://github.com/walinejs/waline) 查找相关内容，本项目不涉及与讨论 `waline` 的详细工作原理。
在生产环境下运行请执行命令：`npm run start`
